version: "3"

services:
  broadcast-box:
    environment:
    - INCLUDE_PUBLIC_IP_IN_NAT_1_TO_1_IP=yes
    image: seaduboi/broadcast-box:latest
    hostname: broadcast-box
    container_name: broadcast-box
    network_mode: "host"
    privileged: true

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    network_mode: "host"
    labels:
      caddy: ${URL}
      caddy.reverse_proxy: "localhost:8080"

  watchtower:
    restart: always
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  caddy_data: {}
