package environment

const (
	// SERVER
	HTTP_ADDRESS                       = "HTTP_ADDRESS"
	HTTPS_REDIRECT_PORT                = "HTTPS_REDIRECT_PORT"
	HTTP_ENABLE_REDIRECT               = "ENABLE_HTTP_REDIRECT"
	NETWORK_TEST_ON_START              = "NETWORK_TEST_ON_START"
	INCLUDE_PUBLIC_IP_IN_NAT_1_TO_1_IP = "INCLUDE_PUBLIC_IP_IN_NAT_1_TO_1_IP"
	DISABLE_STATUS                     = "DISABLED_STATUS"

	// SSL
	USE_SSL  = "USE_SSL"
	SSL_KEY  = "SSL_KEY"
	SSL_CERT = "SSL_CERT"

	// AUTHORIZATION
	STREAM_PROFILE_ACTIVE = "STREAM_PROFILE_ACTIVE"
	STREAM_PROFILE_PATH   = "STREAM_PROFILE_PATH"
	WEBHOOK_URL           = "WEBHOOK_URL"

	// FRONTEND
	DISABLE_FRONTEND = "DISABLE_FRONTEND"
	FRONTEND_PATH    = "FRONTEND_PATH"

	// WEBRTC
	INCLUDE_LOOPBACK_CANDIDATE = "INCLUDE_LOOPBACK_CANDIDATE"
	NETWORK_TYPES              = "NETWORK_TYPES"
	TCP_MUX_FORCE              = "TCP_MUX_FORCE"
	TCP_MUX_ADDRESS            = "TCP_MUX_ADDRESS"
	INTERFACE_FILTER           = "INTERFACE_FILTER"
	UDP_MUX_PORT               = "UDP_MUX_PORT"
	UDP_MUX_PORT_WHIP          = "UDP_MUX_PORT_WHIP"
	UDP_MUX_PORT_WHEP          = "UDP_MUX_PORT_WHEP"
	NAT_1_TO_1_IP              = "NAT_1_TO_1_IP"
	NAT_ICE_CANDIDATE_TYPE     = "NAT_ICE_CANDIDATE_TYPE"

	// TURN/STUN
	STUN_SERVERS            = "STUN_SERVERS"
	TURN_SERVERS            = "TURN_SERVERS"
	TURN_SERVERS_INTERNAL   = "TURN_SERVERS_INTERNAL"
	STUN_SERVERS_INTERNAL   = "STUN_SERVERS_INTERNAL"
	TURN_SERVER_AUTH_SECRET = "TURN_SERVER_AUTH_SECRET"

	// PEERCONNECTION
	APPEND_CANDIDATE = "APPEND_CANDIDATE"

	// DEBUGGING
	DEBUG_INCOMING_API_REQUEST = "DEBUG_INCOMING_API_REQUEST"
	DEBUG_PRINT_ANSWER         = "DEBUG_PRINT_ANSWER"
	DEBUG_PRINT_OFFER          = "DEBUG_PRINT_OFFER"
	DEBUG_PRINT_SSE_MESSAGES   = "DEBUG_PRINT_SSE_MESSAGES"

	// LOGGING
	LOGGING_ENABLED             = "LOGGING_ENABLED"
	LOGGING_DIRECTORY           = "LOGGING_DIRECTORY"
	LOGGING_SINGLEFILE          = "LOGGING_SINGLEFILE"
	LOGGING_NEW_FILE_ON_STARTUP = "LOGGING_NEW_FILE_ON_STARTUP"
	LOGGING_API_ENABLED         = "LOGGING_API_ENABLED"
	LOGGING_API_KEY             = "LOGGING_API_KEY"
)
